### ISSUE TITLE
How do I change the package so the cards get swiped with less "User swiping"

### ISSUE THREAD

**Issue by PhiJoTo** [xrr2016/tcard#14]
For example, I nearly have to swipe the card across the whole screen whereas in Google Photos a centimetre is enough if my finger is moving fast.

**Comment by xrr2016** [comment]
You can  increase the speed here https://github.com/xrr2016/tcard/blob/63a3f552d1a5daa94e2d2760d5cc9bcb5074dcdb/lib/src/cards.dart#L333
