### ISSUE TITLE
Widget Sizes

### ISSUE THREAD

**Issue by aljibbs** [xrr2016/tcard#15]
I have 3 questions.
1. How can I make widget full screen. I have tried double.infinity and MediaQuery width and height but card widgets don't change size.

2. I want to hide sibling widgets (middle and bottom widgets) until the user swipes. Like using IndexedStack instead of the usual Stack. How do I do this with your cards ?

3. Is it possible to disable up and down swipe ?

**Comment by xrr2016** [comment]
> I have 3 questions.
> 
> 1. How can I make widget full screen. I have tried double.infinity and MediaQuery width and height but card widgets don't change size.
> 2. I want to hide sibling widgets (middle and bottom widgets) until the user swipes. Like using IndexedStack instead of the usual Stack. How do I do this with your cards ?
> 3. Is it possible to disable up and down swipe ?

1. Maybe you can warp the widget in a full screen parent.
2. You can modify the middle and back card's default position. https://github.com/xrr2016/tcard/blob/63a3f552d1a5daa94e2d2760d5cc9bcb5074dcdb/lib/src/animations.dart#L21
3. Yes, set a  a static y axis value for the front card.
https://github.com/xrr2016/tcard/blob/63a3f552d1a5daa94e2d2760d5cc9bcb5074dcdb/lib/src/cards.dart#L335

XD : )

**Comment by aljibbs** [comment]
Great, I got it to work.

**Comment by aljibbs** [comment]
Is there a way to make the increase the speed of the drag ?

**Comment by xrr2016** [comment]
> 1. Is there a way correct to increase the speed of the swipe ?
>    I did it by increasing the speed parameter.
> 
> https://github.com/xrr2016/tcard/blob/63a3f552d1a5daa94e2d2760d5cc9bcb5074dcdb/lib/src/cards.dart#L333
> 
> 1. I want to add/build sibling card only after the first card has been swiped off and call a function when the child is built. Simply put, I want the stack number to be 1 at each point in time and call a function after the next child is added.

1. Right.
2. That sound a lot's of work, maybe you should use the code and create a new plugin.  : )

**Comment by aljibbs** [comment]
Great

**Comment by aljibbs** [comment]
Great but what I really wanted to know is where you add cards singly cos the back card is added anytime the front card is swiped.
