### ISSUE TITLE
Controller forward with direction not behaving as expectedly.

### ISSUE THREAD

**Issue by itsatifsiddiqui** [xrr2016/tcard#20]
First of all thank you for the great package.
I'm having an issue please take a look below.
#9 

Suppose we have 6 cards, sometimes when I call forward with Direction.Right, card slides to left, whereas in ONForward callback it detects the direction as Direction.Left. 

Same if I call forward with Direction.Left, card slides to right, where as in ONForward callback it detects the direction as Direction.Right.

Please Look at the last log, I swiped to right but it swiped to the left.
It doesn't happen always but happens sometimes. 

Below are the logs.

- I/flutter ( 7300): 🐛 SWIPING TO LEFT
- I/flutter ( 7300): --------------------------------
- I/flutter ( 7300): 🐛 INFO
- I/flutter ( 7300): SwipDirection.Left
- I/flutter ( 7300): --------------------------------
- I/flutter ( 7300): 🐛 SWIPING TO LEFT
- I/flutter ( 7300): --------------------------------
- I/flutter ( 7300): 🐛 INFO
- I/flutter ( 7300): SwipDirection.Left
- I/flutter ( 7300): --------------------------------
- I/flutter ( 7300): 🐛 SWIPING TO LEFT
- I/flutter ( 7300): --------------------------------
- I/flutter ( 7300): 🐛 SIPING TO Right
- I/flutter ( 7300): --------------------------------
- I/flutter ( 7300): 🐛 INFO
- I/flutter ( 7300): SwipDirection.Left
- I/flutter ( 7300): --------------------------------
- I/flutter ( 7300): 🐛 SWIPING TO Right
- I/flutter ( 7300): --------------------------------
- I/flutter ( 7300): 🐛 INFO
- I/flutter ( 7300): SwipDirection.Left
- I/flutter ( 7300): --------------------------------

**Comment by xrr2016** [comment]
> First of all thank you for the great package.
> I'm having an issue please take a look below.
> #9
> 
> Suppose we have 6 cards, sometimes when I call forward with Direction.Right, card slides to left, whereas in ONForward callback it detects the direction as Direction.Left.
> 
> Same if I call forward with Direction.Left, card slides to right, where as in ONForward callback it detects the direction as Direction.Right.
> 
> Please Look at the last log, I swiped to right but it swiped to the left.
> It doesn't happen always but happens sometimes.
> 
> Below are the logs.
> 
> * I/flutter ( 7300): 🐛 SWIPING TO LEFT
> * I/flutter ( 7300): --------------------------------
> * I/flutter ( 7300): 🐛 INFO
> * I/flutter ( 7300): SwipDirection.Left
> * I/flutter ( 7300): --------------------------------
> * I/flutter ( 7300): 🐛 SWIPING TO LEFT
> * I/flutter ( 7300): --------------------------------
> * I/flutter ( 7300): 🐛 INFO
> * I/flutter ( 7300): SwipDirection.Left
> * I/flutter ( 7300): --------------------------------
> * I/flutter ( 7300): 🐛 SWIPING TO LEFT
> * I/flutter ( 7300): --------------------------------
> * I/flutter ( 7300): 🐛 SIPING TO Right
> * I/flutter ( 7300): --------------------------------
> * I/flutter ( 7300): 🐛 INFO
> * I/flutter ( 7300): SwipDirection.Left
> * I/flutter ( 7300): --------------------------------
> * I/flutter ( 7300): 🐛 SWIPING TO Right
> * I/flutter ( 7300): --------------------------------
> * I/flutter ( 7300): 🐛 INFO
> * I/flutter ( 7300): SwipDirection.Left
> * I/flutter ( 7300): --------------------------------

Updated, please install new version 🥺
