### ISSUE TITLE
New update isn't published because of the same version

### ISSUE THREAD

**Issue by BrunoJurkovic** [xrr2016/tcard#29]
Hey there @xrr2016!

Thanks for merging my PR, but I noticed that the new version isn't published
because the version is the same on the loc and pub.dev site.

Here are the publish logs from your GitHub action.

```
Local version: [1.3.3]
37
Remote version: [1.3.3]
38
Remote & Local versions are equal, skip publishing.
```

**Comment by xrr2016** [comment]
![image](https://user-images.githubusercontent.com/18013127/112919998-ab1f0680-913a-11eb-9abc-435b8e2f7ba2.png)
Updated.
