### ISSUE TITLE
Detect direction of swipe?

### ISSUE THREAD

**Issue by Pebsie** [xrr2016/tcard#4]
Is there any way to detect the direction that the user swipes? I would've thought that onForward and onBack did this, but they both seem to do the same thing. Any ideas?

**Comment by xrr2016** [comment]
> Is there any way to detect the direction that the user swipes? I would've thought that onForward and onBack did this, but they both seem to do the same thing. Any ideas?

Can use an array to save the sliding direction, use `details.delta.dx` to determine the direction when sliding the card, and then use it in the callback function.

I can add this feature this weekend.

**Comment by Pebsie** [comment]
> > Is there any way to detect the direction that the user swipes? I would've thought that onForward and onBack did this, but they both seem to do the same thing. Any ideas?
> 
> Can use an array to save the sliding direction, use `details.delta.dx` to determine the direction when sliding the card, and then use it in the callback function.
> 
> I can add this feature this weekend.

That'd be fantastic! There are a lot of tinder card packages and they're usually pretty poor, but this one is so straight forward and well executed that it seems weird that this is missing. This would make it the best plugin for this purpose.

**Comment by xrr2016** [comment]
> > > Is there any way to detect the direction that the user swipes? I would've thought that onForward and onBack did this, but they both seem to do the same thing. Any ideas?
> > 
> > 
> > Can use an array to save the sliding direction, use `details.delta.dx` to determine the direction when sliding the card, and then use it in the callback function.
> > I can add this feature this weekend.
> 
> That'd be fantastic! There are a lot of tinder card packages and they're usually pretty poor, but this one is so straight forward and well executed that it seems weird that this is missing. This would make it the best plugin for this purpose.
 
Updated. https://github.com/xrr2016/tcard#determine-the-sliding-direction
